argo-cd:
  nameOverride: argocd
  fullnameOverride: argocd
  dex:
    enabled: false
  server:
    ingress:
      # -- Enable an ingress resource for the Argo CD server
      enabled: true
      # -- Additional ingress annotations
      annotations:
        kubernetes.io/ingress.class: "gce"
        kubernetes.io/ingress.global-static-ip-name: zen-dev-gke-0-asm-ingress-gateway-ip-address
        networking.gke.io/managed-certificates: argocd-server
      hosts:
        - argo-cd.labs.lemayian.africa
      paths:
        - /*
      pathType: ImplementationSpecific
      https: false
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: cluster-addons
      spec:
        generators:
        - git:
            repoURL: https://github.com/cs-nerds/five-empty-charts.git
            revision: HEAD
            directories:
            - path: charts/*
              exclude: false
            - path: charts/chart-five
              exclude: true
        template:
          metadata:
            name: '{{ `{{path.basename}}` }}'
          spec:
            project: default
            source:
              repoURL: https://github.com/cs-nerds/five-empty-charts.git
              targetRevision: HEAD
              path: '{{ `{{path}}` }}'
              helm:
                valueFiles:
                  - "broken.values.yaml"
                  - "values.yaml"
                ignoreMissingValueFiles: true
            destination:
              server: https://kubernetes.default.svc
              namespace: '{{ `{{path.basename}}` }}'
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
